language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  hg clone https://code.google.com/p/vim/
  cd vim
  ./configure --with-features=huge
  make
  sudo make install
  cd -

script: |
  vim -Nu <(cat << VIMRC
  set rtp+=vader.vim
  set rtp+=.
  VIMRC) -c 'Vader! test/*' > /dev/null

